[package]
name = "twitch-live"
version = "0.1.3"
description = "A Tauri App"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "twitch_live_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
dotenvy = "0.15"
dotenvy_macro = "0.15"

[dependencies]
tauri = { version = "2", features = ["objc-exception", "wry"], default-features = false }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["full"] }
url = "2"
anyhow = "1"
open = "5"
urlencoding = "2"
toml = "0.8"
dirs = "6"
log = "0.4"
env_logger = "0.11"
tauri-plugin-notification = "2.3.3"

[profile.dev]
incremental = true

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true
opt-level = "s" # Use 3 to optimize performance, z to optimize for size, and s for something in-between.
strip = true
